name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Upload Jacoco to Codecov
        uses: codecov/codecov-action@v2.0.2
        with:
          file: ./target/site/jacoco/jacoco.xml
          flags: unittests