name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mvn-profile: [poi-3, poi-4, poi-5]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build with Maven
        run:
          mvn --batch-mode --update-snapshots -P${{ matrix.profile }} test
          cp
      - name: Upload Jacoco to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./target/site/jacoco-${{ matrix.profile }}/jacoco.xml
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}